// <auto-generated />
using System;
using GestionSallesEmit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionSallesEmit.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260714062455_AjoutMentionParcoursNiveauIndisponibilite")]
    partial class AjoutMentionParcoursNiveauIndisponibilite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionSallesEmit.Models.Cours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Credit")
                        .HasColumnType("integer");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomCours")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParcoursId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParcoursId");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("GestionSallesEmit.Models.Enseignant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("GestionSallesEmit.Models.Indisponibilite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EnseignantId")
                        .HasColumnType("integer");

                    b.Property<string>("HeureDebut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeureFin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Raison")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("EnseignantId");

                    b.ToTable("Indisponibilites");
                });

            modelBuilder.Entity("GestionSallesEmit.Models.Mention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NomMention")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Mentions");
                });

            modelBuilder.Entity("GestionSallesEmit.Models.Parcours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MentionId")
                        .HasColumnType("integer");

                    b.Property<string>("NomParcours")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MentionId");

                    b.ToTable("Parcours");
                });

            modelBuilder.Entity("GestionSallesEmit.Models.Salle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacite")
                        .HasColumnType("integer");

                    b.Property<string>("NomSalle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("GestionSallesEmit.Models.Seance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoursId")
                        .HasColumnType("integer");

                    b.Property<int>("EnseignantId")
                        .HasColumnType("integer");

                    b.Property<string>("HeureDebut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeureFin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SalleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoursId");

                    b.HasIndex("EnseignantId");

                    b.HasIndex("SalleId");

                    b.ToTable("Seances");
                });

            modelBuilder.Entity("GestionSallesEmit.Models.Cours", b =>
                {
                    b.HasOne("GestionSallesEmit.Models.Parcours", "Parcours")
                        .WithMany("Cours")
                        .HasForeignKey("ParcoursId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("GestionSallesEmit.Models.Indisponibilite", b =>
                {
                    b.HasOne("GestionSallesEmit.Models.Enseignant", "Enseignant")
                        .WithMany("Indisponibilites")
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enseignant");
                });

            modelBuilder.Entity("GestionSallesEmit.Models.Parcours", b =>
                {
                    b.HasOne("GestionSallesEmit.Models.Mention", "Mention")
                        .WithMany("Parcours")
                        .HasForeignKey("MentionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mention");
                });

            modelBuilder.Entity("GestionSallesEmit.Models.Seance", b =>
                {
                    b.HasOne("GestionSallesEmit.Models.Cours", "Cours")
                        .WithMany()
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionSallesEmit.Models.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionSallesEmit.Models.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("SalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Enseignant");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("GestionSallesEmit.Models.Enseignant", b =>
                {
                    b.Navigation("Indisponibilites");
                });

            modelBuilder.Entity("GestionSallesEmit.Models.Mention", b =>
                {
                    b.Navigation("Parcours");
                });

            modelBuilder.Entity("GestionSallesEmit.Models.Parcours", b =>
                {
                    b.Navigation("Cours");
                });
#pragma warning restore 612, 618
        }
    }
}
